#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

console.log('🔧 EmailJS Environment Setup Helper');
console.log('=====================================\n');

console.log('This script will help you create a .env file for EmailJS configuration.\n');

console.log('📋 Prerequisites:');
console.log('1. EmailJS account: https://www.emailjs.com/');
console.log('2. Email service configured in EmailJS dashboard');
console.log('3. Email template created in EmailJS dashboard\n');

console.log('📝 You will need these values from your EmailJS dashboard:');
console.log('- Service ID (from Email Services)');
console.log('- Template ID (from Email Templates)');
console.log('- Public Key (from Account settings)\n');

const readline = require('readline');
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const questions = [
  'Enter your EmailJS Service ID: ',
  'Enter your EmailJS Template ID: ',
  'Enter your EmailJS Public Key: '
];

const answers = [];

function askQuestion(index) {
  if (index >= questions.length) {
    createEnvFile();
    return;
  }
  
  rl.question(questions[index], (answer) => {
    if (answer.trim()) {
      answers.push(answer.trim());
      askQuestion(index + 1);
    } else {
      console.log('❌ This field is required. Please try again.\n');
      askQuestion(index);
    }
  });
}

function createEnvFile() {
  const envContent = `# EmailJS Configuration
# Generated by setup-env.js
REACT_APP_EMAILJS_SERVICE_ID=${answers[0]}
REACT_APP_EMAILJS_TEMPLATE_ID=${answers[1]}
REACT_APP_EMAILJS_PUBLIC_KEY=${answers[2]}

# Optional: Test Mode (set to 'true' to skip Firebase Auth and Firestore writes)
REACT_APP_TEST_MODE=false

# Optional: GAS Email WebApp URL (for alternative email sending)
# REACT_APP_GAS_EMAIL_WEBAPP_URL=your_gas_webapp_url_here

# Default Permission Letter Template Link (optional)
# Upload a default permission letter template to Google Drive and set it to "Anyone with link can view"
# Then add the sharing link here
# REACT_APP_DEFAULT_PERMISSION_LETTER_LINK=https://docs.google.com/document/d/1ZWO279HuGWA9Cc2P8VFfvXuFlLJSrnSA/edit

# Firebase Configuration (already configured in firebase.js)
# REACT_APP_FIREBASE_API_KEY=your_firebase_api_key
# REACT_APP_FIREBASE_AUTH_DOMAIN=your_firebase_auth_domain
# REACT_APP_FIREBASE_PROJECT_ID=your_firebase_project_id
# REACT_APP_FIREBASE_STORAGE_BUCKET=your_firebase_storage_bucket
# REACT_APP_FIREBASE_MESSAGING_SENDER_ID=your_firebase_messaging_sender_id
# REACT_APP_FIREBASE_APP_ID=your_firebase_app_id
# REACT_APP_FIREBASE_MEASUREMENT_ID=your_firebase_measurement_id
`;

  const envPath = path.join(__dirname, '.env');
  
  try {
    fs.writeFileSync(envPath, envContent);
    console.log('\n✅ .env file created successfully!');
    console.log('📁 Location:', envPath);
    console.log('\n🔄 Next steps:');
    console.log('1. Restart your development server: npm start');
    console.log('2. Test the booking flow');
    console.log('3. Check the console for any remaining errors');
    console.log('\n📚 For more help, see EMAILJS_SETUP.md');
  } catch (error) {
    console.error('\n❌ Error creating .env file:', error.message);
    console.log('\n📝 Manual setup:');
    console.log('Create a .env file in your project root with:');
    console.log('REACT_APP_EMAILJS_SERVICE_ID=your_service_id');
    console.log('REACT_APP_EMAILJS_TEMPLATE_ID=your_template_id');
    console.log('REACT_APP_EMAILJS_PUBLIC_KEY=your_public_key');
  }
  
  rl.close();
}

console.log('🚀 Starting setup...\n');
askQuestion(0);
